#!/bin/bash
#
# Copyright (c) Microsoft. All rights reserved.
#
# Licensed under the MIT license. See LICENSE.md file in the project root
# for full license information.
# ==============================================================================

. $TEST_ROOT_DIR/run-test-common

set -x -o pipefail -e

MODULE_DIR="$(python -c "import cntk, os, sys; sys.stdout.write(os.path.dirname(os.path.abspath(cntk.__file__)))")"

cd ../../../../bindings/python/doc

sphinx-apidoc "$MODULE_DIR" -o . -f $(find "$MODULE_DIR" -type d -name tests)

sphinx-build -b html -d _build/doctrees -W -j $(nproc) _build/html

ERROR=0

if grep "object at 0x" _build/html/*.html; then
  echo Object addresses leaked into documentation, please fix \(e.g., by
  echo   repeating the signature at the beginning of the docstring\).
  ((ERROR++))
fi

if grep '``' _build/html/*.html; then
  echo Double back-ticks leaked into the documentation. Please check.
  ((ERROR++))
fi

if grep ':[a-z][a-z]*:'; then
   echo Unrendered content leaked into the documentation. Please check.
   ((ERROR++))
fi

((ERROR == 0)) || {
  echo Error\(s\) occurred, stopping.
  false
}

set +x
echo "__COMPLETED__"
